services:
  db:
    container_name: kohlhaas
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: admin
      POSTGRES_DB: kohlhaasDB
    ports:
      - "7777:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d kohlhaasDB" ]
      interval: 5s
      timeout: 5s
      retries: 5
  
volumes:
  pgdata: