name: Kohlhaas CI

on:
   push:
     branches: [ master ]
   pull_request:
     branches: [ master ]
   workflow_dispatch:
       

env:
  DOTNET_VERSION: "10.x"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
           fetch-depth: 0
           
      - name: debugging missing directory
        run: | 
             echo "current git branch:"
             git branch -a
             ls -la
             echo "search current directory for my files:"
             find . -name "*.csproj" -type f
             echo "search home directory for my project:"
             find ~ -name "*.sln" -type f
             find ~ -name "*.csproj" -type f
      
      - name: setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: install dependencies
        run: dotnet restore ${{ env.DOTNET_VERSION }}
      
      - name: build
        run: dotnet build ${{ env.DOTNET_VERSION }} --configuration Release --no-restore
      
      - name: test
        run: dotnet test ${{ env.DOTNET_VERSION }} --configuration Release --no-restore --no-build --verbosity normal --logger trx --results-directory "TestResults-${{ env.DOTNET_VERSION }}"
      
      - name: upload test results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-results-${{ env.DOTNET_VERSION }}
          path: TestResults-${{ env.DOTNET_VERSION }}
        if: ${{ always() }}
          
         
       
